name: josephine-claire-portfolio
region: nyc
static_sites:
  - name: portfolio-frontend
    github:
      repo: clairenogot/nogotjosephineclaire
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: dist
    index_document: index.html
    error_document: index.html
    routes:
      - path: /
    environment_slug: node-js
    envs:
      - key: NODE_VERSION
        value: "20.11.0"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NODE_MODULES_CACHE
        value: "false"
